### ISSUE TITLE
Some notes about gongfuture/Light-Novel-Yuedu-Source

### ISSUE THREAD

**Issue by ZWolken** [gongfuture/Light-Novel-Yuedu-Source#1]
阁下的`gongfuture/Light-Novel-Yuedu-Source`没有开issue功能所以发在这里致歉（
看完后直接删除该issue即可 我并不介意
`www.wenku8.net`在部分网络环境下是可以正常使用的，可见附图
`www.wenku8.net`以及`www.wenku8.cc`这两个网站我个人实际访问下来情况非常玄学，某些网络环境下会存在`www.wenku8.net`可以正常访问反而`www.wenku8.cc`无法正常访问的情况
因此我个人的`阅读`软件内实际是两个网站同时都写了书源并启用着。

若需要进一步讨论的话您可以在您fork的仓库内开个issue并@提及我或者我这边将原仓库的存档状态关闭并开个issue均可
开了存档状态主要还是退酷安以及主要书源之一的`哔哩轻小说`网站开了反爬以及字体混淆 实在是懒得维护（

附图：
![image](https://github.com/gongfuture/gongfuture.github.io/assets/76812845/eeb78935-e7bc-4acd-849c-6bdc1d7c62b7)

**Comment by ZWolken** [comment]
由于寒假一直在忙，拖了这么久才回复属实抱歉
项目仓库我已经解除存档状态并且稍加更新了，不过未加入阁下的Release内容
您可以看看还有什么内容需要更改的您直接开个PR就行

**Comment by gongfuture** [comment]
> 由于寒假一直在忙，拖了这么久才回复属实抱歉
> 项目仓库我已经解除存档状态并且稍加更新了，不过未加入阁下的Release内容
> 您可以看看还有什么内容需要更改的您直接开个PR就行

好的好的
